# https://www.playframework.com/documentation/latest/Configuration

play {
    server {
        http {
            port = 9120
        }
    }
}

couchbase {
  connectionString = "localhost"
  username = "Administrator"
  password = "password"
  bucket = "td-bucket"
  scope = "td-scope"
}